module.exports = {
  mongoConnectionString: process.env.MONGO_CONNECTION_STRING,
  discordBotToken: process.env.DISCORD_BOT_TOKEN,
  youtubeAPIKey: process.env.YOUTUBE_API_KEY,
  animuAPIKey: process.env.ANIMU_API_KEY,
  topGGAPIKey: process.env.TOP_GG_API_KEY,
  nasaAPIKey: process.env.NASA_API_KEY,
  booksAPIKey: process.env.BOOKS_API_KEY,
  websterAPIKey: process.env.WEBSTER_API_KEY,
  deviantartClientID: process.env.DEVIANTART_CLIENT_ID,
  deviantartClientSecret: process.env.DEVIANTART_CLIENT_SECRET,
  githubUsername: process.env.GITHUB_USERNAME,
  githubPassword: process.env.GITHUB_PASSWORD,
  pixivUsername: process.env.PIXIV_USERNAME,
  pixivPassword: process.env.PIXIV_PASSWORD,
  TMBDAPIKey: process.env.TMDB_API_KEY,
  OSUAPIKey: process.env.OSU_API_KEY,
  stackoverflowKey: process.env.STACKOVERFLOW_KEY,
  alphaVantageAPIKey: process.env.ALPHA_VANTAGE_API_KEY,
  openWeatherAPIKey: process.env.OPEN_WEATHER_API_KEY,
  perspectiveAPIKey: process.env.PERSPECTIVE_API_KEY,
  lavalinkPassword: process.env.LAVALINK_PASSWORD,
  botEnv: process.env.BOT_ENV,
};
